package edu.uclm.esi.videochat;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.Before;
import org.hamcrest.core.Is;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By.ByPartialLinkText;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.w3c.dom.html.HTMLElement;

import edu.uclm.esi.videochat.model.Token;
import edu.uclm.esi.videochat.model.User;
import edu.uclm.esi.videochat.springdao.TokenRepository;
import edu.uclm.esi.videochat.springdao.UserRepository;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
public class RegisterTestJava {
	
	
  private WebDriver chrome;
  private WebDriver chrome2;
  private WebDriver chrome3;
  private WebDriver firefox;
  private WebDriver edge;
  
  @Autowired
  UserRepository userRepo; 
  @Autowired
  TokenRepository tokenRepo;
  
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "C:\\Users\\Juan\\git\\TecyDisWeb\\selenium\\chromedriver.exe");
	  System.setProperty("webdriver.gecko.driver", "C:\\Users\\Juan\\git\\TecyDisWeb\\selenium\\geckodriver.exe");
	  System.setProperty("webdriver.edge.driver", "C:\\Users\\Juan\\git\\TecyDisWeb\\selenium\\msedgedriver.exe");
	//edge = new EdgeDriver();
	chrome = new ChromeDriver();
	//firefox = new FirefoxDriver();
    chrome2 = new ChromeDriver();
    chrome3 = new ChromeDriver();
    js = (JavascriptExecutor) chrome;
    js = (JavascriptExecutor) chrome3;
    js = (JavascriptExecutor) chrome2;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    chrome.quit();
    chrome2.quit();
    chrome3.quit();
    //firefox.quit();
    //edge.quit();
  }
    @Test
  public void registroTres() {
	  
	  Optional<User> pepe= userRepo.findByName("Pepe");
	  Optional<User> ana= userRepo.findByName("Ana");
	  Optional<User> lucas= userRepo.findByName("Lucas");
	  
	  if(pepe.isPresent())
		  userRepo.deleteById(pepe.get().getId());
	  if(ana.isPresent())
		  userRepo.deleteById(ana.get().getId());
	  if(lucas.isPresent())
		  userRepo.deleteById(lucas.get().getId());
	  
	  
	    
	  
	     try {
	   		Thread.sleep(2000);
	   	} catch (InterruptedException e) {
	   		// TODO Auto-generated catch block
	   		e.printStackTrace();
	   	}
	  
    chrome.get("https://localhost:7500");
    chrome2.get("https://localhost:7500");
    chrome3.get("https://localhost:7500");
    
    try {
  		Thread.sleep(15000);
  	} catch (InterruptedException e) {
  		// TODO Auto-generated catch block
  		e.printStackTrace();
  	}
    
//    chrome.findElement(By.id("details-button")).click();
//    chrome.findElement(By.id("proceed-link")).click();
    
    
    WebElement linkChrome = chrome.findElement(By.linkText("Crear cuenta"));
    linkChrome.click();
    try {
  		Thread.sleep(1000);
  	} catch (InterruptedException e) {
  		// TODO Auto-generated catch block
  		e.printStackTrace();
  	}
    WebElement cajaPwdChrome = chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[3]"));
    WebElement cajaPwd2Chrome = chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[4]"));
    WebElement cajaEmailChrome = chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[2]"));
    WebElement cajaNombreChrome= chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[1]"));
    WebElement uploadPhotoChrome= chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[5]"));
    try {
  		Thread.sleep(1000);
  	} catch (InterruptedException e) {
  		// TODO Auto-generated catch block
  		e.printStackTrace();
  	}
    cajaNombreChrome.sendKeys("Pepe");
    cajaEmailChrome.sendKeys("pepe@gmail.com");
    cajaPwdChrome.sendKeys("1234");
    cajaPwd2Chrome.sendKeys("1234");
    uploadPhotoChrome.sendKeys("C:\\Users\\Juan\\Pictures\\foto.jpg");
    
  
    WebElement botonChrome = chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button"));
    botonChrome.click();
    
    WebElement linkFirefox = chrome2.findElement(By.linkText("Crear cuenta"));
    linkFirefox.click();
    try {
  		Thread.sleep(1000);
  	} catch (InterruptedException e) {
  		// TODO Auto-generated catch block
  		e.printStackTrace();
  	}
    WebElement cajaPwdFirefox = chrome2.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[3]"));
    WebElement cajaPwd2Firefox = chrome2.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[4]"));
    WebElement cajaEmailFirefox = chrome2.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[2]"));
    WebElement cajaNombreFirefox= chrome2.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[1]"));
    WebElement uploadPhotoFirefox= chrome2.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[5]"));
    try {
  		Thread.sleep(1000);
  	} catch (InterruptedException e) {
  		// TODO Auto-generated catch block
  		e.printStackTrace();
  	}
    cajaNombreFirefox.sendKeys("Ana");
    cajaEmailFirefox.sendKeys("ana@gmail.com");
    cajaPwdFirefox.sendKeys("1234");
    cajaPwd2Firefox.sendKeys("1234");
    uploadPhotoFirefox.sendKeys("C:\\Users\\Juan\\Pictures\\foto.jpg");
    
    
   
    
    WebElement botonFirefox = chrome2.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button"));
    botonFirefox.click();
    
    WebElement linkEdge = chrome3.findElement(By.linkText("Crear cuenta"));
    linkEdge.click();
    try {
  		Thread.sleep(1000);
  	} catch (InterruptedException e) {
  		// TODO Auto-generated catch block
  		e.printStackTrace();
  	}
    WebElement cajaPwdEdge = chrome3.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[3]"));
    WebElement cajaPwd2Edge = chrome3.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[4]"));
    WebElement cajaEmailEdge = chrome3.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[2]"));
    WebElement cajaNombreEdge= chrome3.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[1]"));
    WebElement uploadPhotoEdge= chrome3.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[5]"));
    try {
  		Thread.sleep(1000);
  	} catch (InterruptedException e) {
  		// TODO Auto-generated catch block
  		e.printStackTrace();
  	}
    cajaNombreEdge.sendKeys("Lucas");
    cajaEmailEdge.sendKeys("Lucas@gmail.com");
    cajaPwdEdge.sendKeys("1234");
    cajaPwd2Edge.sendKeys("1234");
    uploadPhotoEdge.sendKeys("C:\\Users\\Juan\\Pictures\\foto.jpg");
    
  
    
    
    WebElement botonEdge = chrome3.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button"));
    botonEdge.click();
    
    
    try {
		Thread.sleep(5000);
	} catch (InterruptedException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
    
   
    
//    chrome.get("https://localhost:7500/users/confirmarCuenta?tokenId=" + tokenIdChrome.getId() );
//    firefox.get("https://localhost:7500/users/confirmarCuenta?tokenId=" + tokenIdFirefox.getId() );
//    edge.get("https://localhost:7500/users/confirmarCuenta?tokenId=" + tokenIdEdge.getId() );
    
    assertThat(chrome.switchTo().alert().getText(), is("Registrado correctamente"));
    assertThat(chrome2.switchTo().alert().getText(), is("Registrado correctamente"));
    assertThat(chrome3.switchTo().alert().getText(), is("Registrado correctamente"));
    //assertThat(chrome.findElement(By.cssSelector(".oj-hybrid-padding > h1")).getText(), is("Login"));
  }
  
  public void llamadaRechazo() {
	  hacerLogin(chrome, "Pepe", "1234");
	  hacerLogin(firefox, "Ana","1234");
	  
	  try {
			Thread.sleep(500);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	  WebElement poci = chrome.findElement(By.linkText(""));
	  poci.click();
	  
	  
	  WebElement ale = firefox.findElement(By.linkText(""));
  }
  
  public void llamadaAceptacion() {
	  
  }
  
  private void hacerLogin(WebDriver driver, String nombre, String contraseña) {
	  driver.get("https://localhost:7500/");

	  //  chrome.findElement(By.id("details-button")).click();
	  //  chrome.findElement(By.id("proceed-link")).click();


	  driver.manage().window().setSize(new Dimension(1184, 683));
	  driver.findElement(By.cssSelector(".oj-hybrid-padding")).click();
	  driver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).clear();
	  driver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).sendKeys(nombre);
	  driver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).clear();
	  driver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).sendKeys(contraseña);
	  driver.findElement(By.cssSelector("button")).click();

	  driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);


  }
  
  
  
}